// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'center': string;
  'logo': string;
  'oneColumn': string;
  'threeColumn': string;
  'twoColumn': string;
}
export const cssExports: CssExports;
export default cssExports;
